# Generated by Django 6.0.4 on 2026-04-22 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_units', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('customer', 'Customer'), ('employee', 'Employee'), ('provider', 'Provider')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatchPurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_of_units', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to='home.batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='home.product'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.batch')),
            ],
        ),
        migrations.CreateModel(
            name='UnitSellingRecordsUnits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('entity', models.CharField(choices=[('customer', 'Customer')], max_length=20)),
                ('quantity_of_units', models.PositiveIntegerField()),
                ('purchase_price', models.FloatField()),
                ('batchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='home.batch')),
                ('unitid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='home.unit')),
            ],
        ),
    ]
