# Generated by Django 6.0.4 on 2026-04-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorybatchpurchaserecord',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='unitsellingrecordsunits',
            name='batchid',
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='set_by',
        ),
        migrations.RemoveField(
            model_name='provider_request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='unitsellingrecordsunits',
            name='unitid',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='InventoryBatchPurchaseRecord',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.DeleteModel(
            name='provider_request',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.DeleteModel(
            name='UnitSellingRecordsUnits',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
