# Generated by Django 6.0.4 on 2026-04-25 12:40

import django.db.models.deletion
import src.applications.main.logic.models.model_user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitperbatch', models.IntegerField()),
                ('acquisition_price', models.FloatField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, limit_choices_to={'role': src.applications.main.logic.models.model_user.UserRoles['CUSTOMER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_batches', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('provider', models.ForeignKey(blank=True, limit_choices_to={'role': src.applications.main.logic.models.model_user.UserRoles['CUSTOMER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
