# Generated by Django 6.0.4 on 2026-04-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('FRUITS_AND_VEGETABLES', 'Frutas y vegetales'), ('LACTEOUS', 'Lacteos'), ('GROCERY_AND_GOURMET', 'Grocery & Gourmet Food'), ('ELECTRONIC_AND_TECH', 'Electronics & Tech'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes'), ('JEWELRY', 'Jewelry'), ('HOME_AND_KITCHEN', 'Home & Kitchen'), ('TOOLS_AND_HOME_IMPROVEMENT', 'Tools & Home Improvement'), ('FURNITURE', 'Furniture'), ('BOOKS', 'Books'), ('VIDEO_GAMES', 'Video Games'), ('MUSIC', 'Music'), ('MOVIES_AND_TV', 'Movies & TV'), ('BEAUTY_AND_PERSONAL_CARE', 'Beauty & Personal Care'), ('HEALTH_AND_HOUSEHOLD', 'Health & Household'), ('TOYS_AND_GAMES', 'Toys & Games'), ('BABY_PRODUCTS', 'Baby Products'), ('SPORTS_AND_OUTDOORS', 'Sports & Outdoors'), ('AUTOMOTIVE', 'Automotive'), ('PET_SUPPLIES', 'Pet Supplies'), ('OFFICE_PRODUCTS', 'Office Products'), ('INDUSTRIAL_AND_SCIENTIFIC', 'Industrial & Scientific')], max_length=40),
        ),
    ]
