# Generated by Django 6.0.4 on 2026-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACEPTED', 'Acepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
    ]
