# Generated by Django 6.0.4 on 2026-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20),
        ),
    ]
