# Generated by Django 6.0.4 on 2026-04-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Acepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LACTEOS', 'Lacteos'), ('CARNES', 'carnes'), ('VINOS', 'Vinos')], max_length=20),
        ),
    ]
