# Generated by Django 6.0.4 on 2026-04-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='batch',
            table='batch',
        ),
    ]
