# Generated by Django 6.0.4 on 2026-04-28 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('admin', 'System Administrator'), ('store_manager', 'Store Manager'), ('order_manager', 'Order Manager'), ('inventory_manager', 'Inventory Manager'), ('customer_support', 'Customer Support'), ('logistics', 'Logistics / Shipping'), ('content_manager', 'Content Manager'), ('finance', 'Finance / Accounting')], default='store_manager', max_length=20)),
                ('hired_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
